name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Log in to Docker Hub
      run: echo "DOCKER_USERNAME=sankar0812" >> $GITHUB_ENV && echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV && docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Push the Docker image to Docker Hub
      run: docker push my-image-name:$(date +%s)
